# Application Name
spring.application.name=Skill6_LibraryMVC

# Server Port
server.port=8080

# Enable colored console output
spring.output.ansi.enabled=always

# Logging Level
logging.level.org.springframework=INFO

# Disable Thymeleaf cache (only if using templates)
spring.thymeleaf.cache=false